const resList = [
  {
    id: 1,
    name: "Spice Villa",
    cuisine: "Indian",
    priceRange: "$$",
    price: 345,
    deliveryTime: "30-40 min",
    rating: 3.2,
    imageId: "cld-sample-4.jpg",
  },
  {
    id: 2,
    name: "Pasta Palace",
    cuisine: "Italian",
    priceRange: "$$",
    price: 410,
    deliveryTime: "25-35 min",
    rating: 4.3,
    imageId: "cld-sample-5.jpg",
  },
  {
    id: 3,
    name: "Sushi World",
    cuisine: "Japanese",
    priceRange: "$$$",
    price: 580,
    deliveryTime: "40-50 min",
    rating: 4.8,
    imageId: "cld-sample-6.jpg",
  },
  {
    id: 4,
    name: "Burger Hub",
    cuisine: "American",
    priceRange: "$",
    price: 220,
    deliveryTime: "20-30 min",
    rating: 4.1,
    imageId: "cld-sample-7.jpg",
  },
  {
    id: 5,
    name: "Taco Fiesta",
    cuisine: "Mexican",
    priceRange: "$",
    price: 190,
    deliveryTime: "25-35 min",
    rating: 4.4,
    imageId: "cld-sample-8.jpg",
  },
  {
    id: 6,
    name: "Dragon Express",
    cuisine: "Chinese",
    priceRange: "$$",
    price: 340,
    deliveryTime: "30-40 min",
    rating: 4.2,
    imageId: "cld-sample-9.jpg",
  },
  {
    id: 7,
    name: "The Salad Bar",
    cuisine: "Healthy",
    priceRange: "$$",
    price: 270,
    deliveryTime: "20-30 min",
    rating: 4.0,
    imageId: "cld-sample-10.jpg",
  },
  {
    id: 8,
    name: "BBQ Nation",
    cuisine: "Grill",
    priceRange: "$$$",
    price: 590,
    deliveryTime: "35-45 min",
    rating: 4.7,
    imageId: "cld-sample-11.jpg",
  },
  {
    id: 9,
    name: "Pizza Mania",
    cuisine: "Italian",
    priceRange: "$",
    price: 275,
    deliveryTime: "20-30 min",
    rating: 4.3,
    imageId: "cld-sample-12.jpg",
  },
  {
    id: 10,
    name: "Shawarma House",
    cuisine: "Middle Eastern",
    priceRange: "$",
    price: 185,
    deliveryTime: "25-35 min",
    rating: 4.5,
    imageId: "cld-sample-13.jpg",
  },
  {
    id: 11,
    name: "Curry Corner",
    cuisine: "Indian",
    priceRange: "$$",
    price: 310,
    deliveryTime: "30-40 min",
    rating: 4.2,
    imageId: "cld-sample-14.jpg",
  },
  {
    id: 12,
    name: "Pho Delight",
    cuisine: "Vietnamese",
    priceRange: "$$",
    price: 360,
    deliveryTime: "30-40 min",
    rating: 4.6,
    imageId: "cld-sample-15.jpg",
  },
  {
    id: 13,
    name: "Dosa Plaza",
    cuisine: "South Indian",
    priceRange: "$",
    price: 200,
    deliveryTime: "20-25 min",
    rating: 4.4,
    imageId: "cld-sample-16.jpg",
  },
  {
    id: 14,
    name: "Kebab Express",
    cuisine: "Turkish",
    priceRange: "$$",
    price: 425,
    deliveryTime: "30-35 min",
    rating: 4.3,
    imageId: "cld-sample-17.jpg",
  },
  {
    id: 15,
    name: "Pancake Story",
    cuisine: "Desserts",
    priceRange: "$",
    price: 160,
    deliveryTime: "15-25 min",
    rating: 4.6,
    imageId: "cld-sample-18.jpg",
  },
  {
    id: 16,
    name: "Wrap n Roll",
    cuisine: "Fast Food",
    priceRange: "$",
    price: 245,
    deliveryTime: "20-30 min",
    rating: 4.1,
    imageId: "cld-sample-19.jpg",
  },
  {
    id: 17,
    name: "Ramen Street",
    cuisine: "Japanese",
    priceRange: "$$",
    price: 465,
    deliveryTime: "30-40 min",
    rating: 4.7,
    imageId: "cld-sample-20.jpg",
  },
  {
    id: 18,
    name: "Waffle World",
    cuisine: "Desserts",
    priceRange: "$",
    price: 150,
    deliveryTime: "15-20 min",
    rating: 4.5,
    imageId: "cld-sample-21.jpg",
  },
  {
    id: 19,
    name: "Falafel Factory",
    cuisine: "Mediterranean",
    priceRange: "$$",
    price: 335,
    deliveryTime: "25-35 min",
    rating: 4.2,
    imageId: "cld-sample-22.jpg",
  },
  {
    id: 20,
    name: "Steak House",
    cuisine: "American Grill",
    priceRange: "$$$",
    price: 600,
    deliveryTime: "40-50 min",
    rating: 4.8,
    imageId: "cld-sample-23.jpg",
  },
];

export default resList